### ISSUE TITLE
Handler Custom 404 page error

### ISSUE THREAD

**Issue by FrenchNicky** [adonisjs/http-server#22]
## Package version
Adonisjs 5
@adonisjs/core@^5.0.0-preview-rc
@adonisjs/http-server@^3.0.1

## Node.js and npm version
Node.js: v14.8.0
npm: v6.14.7

## Sample Code (to reproduce the issue)

Exceptions/Handler.ts
```
import Logger from '@ioc:Adonis/Core/Logger'
import HttpExceptionHandler from '@ioc:Adonis/Core/HttpExceptionHandler'

export default class ExceptionHandler extends HttpExceptionHandler {

        protected disableStatusPagesInDevelopment = false
	protected statusPages = {
		'404': 'errors.not-found',
		'500..599': 'errors.server-error',
	}

	constructor () {
		super(Logger)
	}
}
```
Server errors correctly display the custom error page.
404 errors only display an error message: 

`E_ROUTE_NOT_FOUND: Cannot GET: /test`

**Comment by thetutlage** [comment]
Will pick up during the weekend
