### ISSUE TITLE
Not terminating request with 304 HTTP status and JSON response body

### ISSUE THREAD

**Issue by steschwa** [adonisjs/http-server#25]
## Package version
Fresh `yarn create adonis-ts-app ...` install
```json
"devDependencies": {
    "@adonisjs/assembler": "^3.0.0",
    "adonis-preset-ts": "^1.1.0",
    "pino-pretty": "^4.3.0",
    "typescript": "^4.0.5",
    "youch": "^2.1.1",
    "youch-terminal": "^1.0.1"
  },
  "dependencies": {
    "@adonisjs/core": "^5.0.4-preview-rc",
    "@adonisjs/repl": "^1.0.0",
    "proxy-addr": "^2.0.6",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19"
  }
```

## Node.js and npm version
Node **v14.5.0**
NPM **v6.14.8**
Yarn **v1.22.10**

## Sample Code (to reproduce the issue)
In your `routes.ts / Controller`:

```ts
import Route from "@ioc:Adonis/Core/Route"

Route.get("/", async ({ response }) => {
    return response.status(304).send({
        status: "NOT_MODIFIED",
        whatever: "Body you want to send"
    })
})
```

## Description

Like you pointed out in https://github.com/adonisjs/http-server/blob/develop/src/Response/index.ts#L202, a response with **304 HTTP status** should not include a body. However if you pass something which is not a plain `String` or `Buffer` the Adonis HTTP server logs a `The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Object` error. That's because `ServerResponse.end(body)` only supports sending a stringified or Buffer body. Also there's no response sent at all (causing the request to terminate after a timeout or being infinite).

I suggest just omitting the body for **304** responses.
If you want i'm gonna open a PR.

**Comment by thetutlage** [comment]
Thanks for sharing the exact code to reproduce the error. I confirm it is a bug and will push the fix out soon :)
