### ISSUE TITLE
Feature/Bug - where route does not regex correctly

### ISSUE THREAD

**Issue by darklight9811** [adonisjs/http-server#30]
I'm trying to do a dynamic based route where it is matching a nested directory. For example, I could have:
```
/export
/export/dir1
/export/dir1/dir2
/export/dir1/dir2/etc
```

All being matched by the same route controller. I'm trying to do it using:
``` ts
Route.get("/export/:path?", "export.controller.index").where("path", ".*");
```

Similar to what laravel proposes if you need this:
https://laravel.com/docs/8.x/routing#parameters-encoded-forward-slashes

But the router match ignores it and doesn't find the route

**Comment by thetutlage** [comment]
This happens when you consider AdonisJS to be a clone of Laravel 😄 

```ts
Route.get('export/*', ({ params }) => {
  console.log(params['*'])
})
```

**Comment by darklight9811** [comment]
- update the adonisjs documentation (v5 also), I was reading the entire source code trying to find this and couldn't also.
- don't discriminate nor joke around being a "laravel clone", that's what got you a lot of your popularity, and a lot of developers are bailing out because they are seeing you distancing yourself from being a laravel clone. I had a lot of friends that were kept in PHP because they couldn't find a good framework equivalent in node, when they met adonis, they came back, but are bailing out again because of the distancing.

**Comment by thetutlage** [comment]
Well, what I said was a light hearted statement. 

I do accept that AdonisJS is inspired by Laravel, but no interest in being a clone. Also, AdonisJS is not for everyone. So if you or your friends feels like bailing out, then feel free to use whatever you like 🙂
