### ISSUE TITLE
Duplicate route name error when using `.resouce()` in `.group()` with `.prefix()`

### ISSUE THREAD

**Issue by McSneaky** [adonisjs/http-server#33]
Duplicate route name error when using `.resouce()` in `.group()` with `.prefix()`

It seems to be problem with `.resource()` only, since with everything else grouping and prefixing works perfectly fine

> RouterException: E_DUPLICATE_ROUTE_NAME: Duplicate route name "foobar.index"

## Package version

```jsonc
"@adonisjs/core": "^5.0.4-preview-rc-2.1",
// http-server version
"@adonisjs/http-server": "4.0.9"
```

## Node.js and npm version
NPM: `6.14.11`
NodeJS: `v15.6.0`

## Sample Code (to reproduce the issue)

```js
// routes.ts
import Route from '@ioc:Adonis/Core/Route'

Route.group(() => {
  Route.resource('foobar', 'FooBarController')
}).prefix('v1')

Route.group(() => {
  Route.resource('foobar', 'SomeOtherController')
}).prefix('v2')
```

**Comment by thetutlage** [comment]
Sorry for the late reply.

Yes. The `Route.resource` method gives name to all the registered routes. Also, there is no way for a resource to know, if it is inside a group or not and there you will have to give the group a name to generate unique names.

```ts
Route.group(() => {
  Route.resource('foobar', 'FooBarController')
})
 .prefix('v1')
 .as('v1') // 👈

Route.group(() => {
  Route.resource('foobar', 'SomeOtherController')
})
 .prefix('v2')
 .as('v2') // 👈
```

**Comment by thetutlage** [comment]
Infact docs does mention this https://preview.adonisjs.com/guides/http/routing#naming-route-groups

**Comment by McSneaky** [comment]
Aah.. Welp.. Missed that from doc somehow 😐 

Anyway, closing since it's not really an issue, just need to use `.as()`
