### ISSUE TITLE
Auth middleware not recognized and not working

### ISSUE THREAD

**Issue by romch007** [adonisjs/http-server#37]
I just installed the auth module using the api guard and redis for storage. When I try to add the middleware function to a route in `routes.ts`, VSCode give me an error about the types, and the middleware is not throwing error for unauthorized request. I added the auth middleware to `registedNamed` like in the example.

![image](https://user-images.githubusercontent.com/38137329/107844650-93cbca00-6dd5-11eb-90c1-b74491e3f74f.png)

## Package version
`@adonisjs/core`: 5.0.4-preview-rc
`@adonisjs/auth`: 5.1.1

## Node.js and npm version
nodejs: v14.15.4
npm: 6.14.10
(yarn: 1.22.10)
## Sample Code (to reproduce the issue)
```typescript
// routes.ts
Route.resource('admins', 'AdminsController').apiOnly().middleware('auth')
// kernel.ts
Server.middleware.registerNamed({ auth: 'App/Middleware/Auth' })
```

**Comment by RomainLanz** [comment]
Hey @romch007! 👋 

This is not how you apply a middleware to a resource's route.

```ts
Route
  .resource('users', 'UsersController')
  .middleware({ '*': ['auth'] })
```

➡ https://preview.adonisjs.com/guides/http/routing#applying-middleware-to-route-resources

**Comment by romch007** [comment]
Thank you ! I missed this paragraph of the doc 😅
