### ISSUE TITLE
makeUrl error in types

### ISSUE THREAD

**Issue by Xstoudi** [adonisjs/http-server#40]
The `makeUrl` signature indicate that the second parameter can be a `MakeUrlOptions` :
```ts
public makeUrl(
  routeIdentifier: string,
  params?: any[] | MakeUrlOptions,
  options?: MakeUrlOptions
): string
```

But when passing a `MakeUrlOptions` as a second parameter:
```ts
router.makeUrl('/posts', { prefixUrl: '/api' })
```
it returns `/posts` when `/api/posts` is expected.

## Package version
v5.2.1

## Node.js and npm version
v15.11.0

## Sample Code (to reproduce the issue)
```ts
router.makeUrl('/posts', { prefixUrl: '/api' }) // /posts
```
and
```ts
router.makeUrl('/posts', undefined, { prefixUrl: '/api' }) // /api/posts
```

**Comment by thetutlage** [comment]
Closing since not actionable
