### ISSUE TITLE
Add 'requestBody' to RequestContract interface ('@ioc:Adonis/Core/Request' typings)

### ISSUE THREAD

**Issue by pavel-voronin** [adonisjs/http-server#43]
## Why this feature is required (specific use-cases will be appreciated)?

It's very convenient to use ES6's Object Destructuring in controllers:

```ts
...
  public async register({
    request: {
      requestBody: { username, password },
    },
    response,
  }: HttpContextContract) {
    await UserService.create({ username, password })

    response.status(204)
  }
...
```

## Have you tried any other work arounds?

`typings/Request.d.ts`:
```ts
declare module '@ioc:Adonis/Core/Request' {
  export interface RequestContract {
    requestBody: Record<string, any>
  }
}
```

## Are you willing to work on it with little guidance?

No

**Comment by thetutlage** [comment]
Not something I would like to add to the core. However, you can add it using getters and macros. https://docs.adonisjs.com/guides/request#extending-request-class
