### ISSUE TITLE
Route.makeUrl doesn't seem to work

### ISSUE THREAD

**Issue by sollidsnake** [adonisjs/http-server#47]
## Package version
    "@adonisjs/core": "^5.3.0",
    "@adonisjs/repl": "^3.1.0",
    "@adonisjs/assembler": "^5.0.0",
    "adonis-preset-ts": "^2.1.0",

## Node.js and npm version
node 14.15.1
npm 6.14.8

## Sample Code (to reproduce the issue)
Create a route:
```typescript
Route.get('/test', 'TestController.index').as('test')
```

Create a controller
```typescript
import { HttpContextContract } from '@ioc:Adonis/Core/HttpContext'

export default class TestController {
  public async index({}: HttpContextContract) {
    return { hello: 'from TestController.index' }
  }
}
```

Try to call generate the url either using the controller method or name, as stated in the docs:
```typescript
Route.makeUrl('test')
Route.makeUrl('TestController.index')
```
Both commands above fail with the following error:
```
IocLookupException: E_IOC_LOOKUP_FAILED: Cannot resolve "Adonis/Core/Route" namespace from the IoC Container

at /home/jesse/code/stocks/server-adonis/commands/TestCommand.ts(anonymous):1
1
2  import Route from '@ioc:Adonis/Core/Route'
3  import { BaseCommand } from '@adonisjs/core/build/standalone'
4
5  export default class TestCommand extends BaseCommand {
6    /**
7     * Command name is used to run the command
```

**Comment by RomainLanz** [comment]
Hey @sollidsnake! 👋🏻 

Please, ensure that you are [booting the application inside your command](https://docs.adonisjs.com/guides/ace-commandline#booting-the-app-within-the-command) and to [move your Route's import inside the handler](https://docs.adonisjs.com/guides/ace-commandline#top-level-imports-are-not-allowed).

**Comment by sollidsnake** [comment]
Oh, you're right, I had missed that. I changed loadApp to true but now I'm getting another error saying the route doesn't exist:
```
RouterException: E_CANNOT_FIND_ROUTE: Cannot find route for "test" identifier

at /home/jesse/code/stocks/server-adonis/commands/TestCommand.ts(TestCommand.run):30
25       */
26      stayAlive: false,
27    }
28
29    public async run() {
30      this.logger.info(Route.makeUrl('test'))
31    }
32  }
33
```

**Comment by thetutlage** [comment]
You can write this line of code. https://github.com/adonisjs/core/blob/develop/commands/ListRoutes.ts#L120. You can also use the list routes command as an inspiration

**Comment by thetutlage** [comment]
Will close the issue for now. Also, please use the discussions forum for asking questions. We keep Github issues just for tracking verified bugs :)
