### ISSUE TITLE
Redirect with 4xx not working

### ISSUE THREAD

**Issue by kwissem1** [adonisjs/http-server#49]
## Prerequisites

We do our best to reply to all the issues on time. If you will follow the given guidelines, the turn around time will be faster.

- Lots of raised issues are directly not bugs but instead are design decisions taken by us.
- Make use of our [forum](https://forum.adonisjs.com/), or [discord server](https://discord.me/adonisjs), if you are not sure that you are reporting a bug.
- Ensure the issue isn't already reported.
- Ensure you are reporting the bug in the correct repo.

*Delete the above section and the instructions in the sections below before submitting*

## Package version
5.5.7

## Node.js and npm version
14.18.1

## Sample Code (to reproduce the issue)
`
Route.get('/test', async ({ response }) => {
    return response.status(404).redirect().toPath('/path')
})
`

Response: Redirecting to /path

**Comment by RomainLanz** [comment]
Hey @kwissem1! 👋🏻 

If you are not more describing your issue, we will keep closing it.

Redirecting somewhere should be a `301`, `302`, `307` or `308`.
It makes no sense to send back a `404` when redirecting.
