### ISSUE TITLE
Support uppercase/lowercase UUIDs as per RFC spec

### ISSUE THREAD

**Issue by AlanNeads** [adonisjs/http-server#50]
https://github.com/adonisjs/http-server/blob/eb89bd3d2b28b531c68a382ad6148807e8852dd0/src/Router/Matchers.ts#L34

Suggestion would be
```js
match: /^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$/
```

[RFC 4122 spec](https://datatracker.ietf.org/doc/html/rfc4122) defines the characters as case insensitive

**Comment by thetutlage** [comment]
Yes, that makes sense :)

How about also adding the `cast` method to always convert the value to lowercase as per this 👇

![CleanShot 2021-11-15 at 05 42 56@2x](https://user-images.githubusercontent.com/1706381/141704843-81b085c5-1824-4282-b681-b65ebe94b492.png)

**Comment by thetutlage** [comment]
Fixed in https://github.com/adonisjs/http-server/pull/53
