### ISSUE TITLE
Cyrillic parameters

### ISSUE THREAD

**Issue by DZ8540** [adonisjs/http-server#59]
## Why this feature is required (specific use-cases will be appreciated)?
Current version adonisJS not supported Cyrillic parameters

Example: 
<img width="646" alt="image" src="https://user-images.githubusercontent.com/50152205/167152356-7e74c56a-ede7-4379-9778-ac2bd86313f5.png">

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/50152205/167152254-e8c4cba3-e3c1-4880-99da-2c415f5184a1.png">

Users should use decodeURIComponent function for decode any Cyrillic symbols in url

Example:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/50152205/167152751-a0ba87d8-1b84-467a-bd23-77d1d3eb5015.png">

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/50152205/167152804-8473d74b-e992-428a-a988-b7d368833b16.png">

You can do it by default and then everyone will be happy :D

Also we can create global middleware, where we can change params for always decoding it, if it is possible.

**Comment by michael-azogu** [comment]
@DZ8540 what did you use to take the screenshot & what theme do you use for vscode 🤝

**Comment by michael-azogu** [comment]
> @DZ8540 what did you use to take the screenshot & what theme do you use for vscode 🤝

is it a mac thing

**Comment by DZ8540** [comment]
Screenshot - mac system, theme - Electron vue
https://marketplace.visualstudio.com/items?itemName=icao.electron-vue

**Comment by michael-azogu** [comment]
> Screenshot - mac system, theme - Electron vue https://marketplace.visualstudio.com/items?itemName=icao.electron-vue

one more thing, is it possible to switch off italicization of all tokens
