### ISSUE TITLE
HttpContext & Route.makeUrl Parse Two Different Param Names When File Extension Is Included

### ISSUE THREAD

**Issue by tomgobich** [adonisjs/http-server#67]
Came across a use-case via a [GH Discussion](https://github.com/adonisjs/core/discussions/4031) where if there's a file extension added to the end of a route param name the HttpContext will exclude the file extension from the param name. However, the URL generator via `Route.makeUrl` includes the file extension in the param name.

## Package version
```
@adonisjs/core: ^5.9.0
@adonisjs/repl: ^3.1.11
@adonisjs/session: ^6.4.0
@adonisjs/shield: ^7.1.0
@adonisjs/view: ^6.2.0
```

## Node.js and npm version
Node: v16.13.0
NPM: v8.1.0

## Sample Code (to reproduce the issue)
For the route definition GET: /test/:slug.html the HttpContext considers slug the param name whereas the URL generator via Route.makeUrl considers slug.html the param name

```ts
Route.get('/', async ({ response }) => {
  let failedUrl = ''

  try {
    // fails because it's expecting 'slug.html' as param name
    failedUrl = Route.makeUrl('test', { slug: 'somevalue' })
  } catch (error) {
    console.error({ error })
  }

  // works, but ends up excluding `.html` from final url output 
  // since it's considered a part of the param name
  const workingUrl1 = Route.makeUrl('test', { 'slug.html': 'somevalue' })
  const workingUrl2 = Route.makeUrl('test', ['somevalue'])

  return response.json({
    failedUrl,    // output: ""                 expected: "/test/somevalue.html"
    workingUrl1,  // output: "/test/somevalue"  expected: "/test/somevalue.html"
    workingUrl2   // output: "/test/somevalue"  expected: "/test/somevalue.html"
  })
})

Route.get('/test/:slug.html', async ({ response, params }) => {
  return response.json(params) // output: { slug: "somevalue" }  expected: { slug: "somevalue" }
}).as('test')
```

## BONUS (a sample repo to reproduce the issue)
[Here is a sample repo for the above example](https://github.com/tomgobich/route-params-parsed-differently-example)

**Comment by thetutlage** [comment]
Thanks for a sharing a detailed example. Indeed a bug and will be working on it

**Comment by thetutlage** [comment]
Going to be released in v6
