### ISSUE TITLE
Consider changing type RequestContract.qs() from Record<string, any> to more strict type

### ISSUE THREAD

**Issue by beam41** [adonisjs/http-server#69]
## Why this feature is required (specific use-cases will be appreciated)?
I happen to get and error where I accidentally use value with type of string in place where it needs number which I get value from `RequestContract.qs()`. It doesn't get detected because `qs()` has value type of any which always pass type check.

This is also quite misleading because `qs()` is always string or string[].

This also applied to `params` I think.

Rare case that might need to consider: If we just set return type to `Record<string, string | string[] | undefined>` it will break when we use `updateQs()` with we insert non string value, TypeScript still think it all string.

## Have you tried any other work arounds?
I can override with
`{ request: { qs: () => Record<string, string | string[] | undefined> } } & HttpContextContract`

## Are you willing to work on it with little guidance?
I don't have time to, sorry.

**Comment by thetutlage** [comment]
This is intentional, because if you want actual type safety, you should opt for runtime validation using the validator.

The validator ensures that types are 100% valid, since they are backed by runtime validations
