### ISSUE TITLE
Make Request method parseQueryString configurable

### ISSUE THREAD

**Issue by enixsoft** [adonisjs/http-server#73]
## Prerequisites

Currently AdonisJS parses query strings in requests by default in @adonisjs/http-server/build/src/Request/index.js method parseQueryString using package [qs](https://www.npmjs.com/package/qs): 
```
parseQueryString() {
    if (this.parsedUrl.query) {
        this.updateQs(qs_1.default.parse(this.parsedUrl.query));
        this.originalRequestData = { ...this.requestData };
    }
}
```
But the parse method of qs here is not configurable at all, even though the package offers many options:
```
interface IParseOptions {
    comma?: boolean | undefined;
    delimiter?: string | RegExp | undefined;
    depth?: number | false | undefined;
    decoder?: ((str: string, defaultDecoder: defaultDecoder, charset: string, type: 'key' | 'value') => any) | undefined;
    arrayLimit?: number | undefined;
    parseArrays?: boolean | undefined;
    allowDots?: boolean | undefined;
    plainObjects?: boolean | undefined;
    allowPrototypes?: boolean | undefined;
    parameterLimit?: number | undefined;
    strictNullHandling?: boolean | undefined;
    ignoreQueryPrefix?: boolean | undefined;
    charset?: 'utf-8' | 'iso-8859-1' | undefined;
    charsetSentinel?: boolean | undefined;
    interpretNumericEntities?: boolean | undefined;
}
```

## Why this feature is required (specific use-cases will be appreciated)?
My use case is to allow comma separated values for array so instead of unnecessary long query strings like:
`someArray[]=1&someArray[]=2&someArray[]=3`
I can just send
`someArray=1,2,3`

## Have you tried any other work arounds?
My work around is this hack to override parseQueryString method in Request class using macro.
In my AppProvider.ts:
```
public async boot() {
    const Request = this.app.container.use('Adonis/Core/Request')

    Request.macro('parseQueryString', function () {
      if (this.parsedUrl.query) {
        this.updateQs(qs.parse(this.parsedUrl.query, { comma: true }))
        // @ts-ignore
        this.originalRequestData = { ...this.requestData }
      }
    })
  }
```

## Solution
Add optional "queryString" object of type QueryStringConfig (this is already used in @adonisjs/bodyparser package) to RequestConfig (part of ServerConfig in config/app.ts).
and that could be used in relevant line of parseQueryString method:
`this.updateQs(qs_1.default.parse(this.parsedUrl.query, this.config.queryString || {}));`

**Comment by ashishnimrot** [comment]
**Create a Configuration File:**
- In config/queryParser.ts, export the configuration options.

`export default {
  comma: true,
  // Other qs options...
}
`


**Extend the Request Class:**

- In app/Extensions/Request.ts, extend the AdonisJS Request class.

`import { Request } from '@adonisjs/http-server/build/standalone'
import qs from 'qs'
import Config from '@ioc:Adonis/Core/Config'

class ExtendedRequest extends Request {
  public parseQueryString(): void {
    const options = Config.get('queryParser', {})
    if (this.parsedUrl.query) {
      this.updateQs(qs.parse(this.parsedUrl.query, options))
      this.originalRequestData = { ...this.requestData }
    }
  }
}

export default ExtendedRequest
`

**Register the Extended Request Class:**

- In start/kernel.ts, register your extended Request class.

`import { IocContract } from '@adonisjs/fold'
import { ApplicationContract } from '@ioc:Adonis/Core/Application'

export default class Kernel {
  constructor(protected app: ApplicationContract) {}

  public register(): void {
    const Ioc = this.app.container as unknown as IocContract
    Ioc.alias('Adonis/Core/Request', 'App/Extensions/Request')
  }
}
`

**Comment by thetutlage** [comment]
It is configurable in the latest release of this package. https://github.com/adonisjs/http-server/blob/develop/src/types/server.ts#L98

For older versions you can use the workaround shared by @ashishnimrot
