### ISSUE TITLE
flushHeaders does not send headers over the network

### ISSUE THREAD

**Issue by stropitek** [adonisjs/http-server#75]
## Package version
@adonisjs/http-server@5.12.0

## Node.js and npm version
node@18.17.1, npm@9.6.7

## Sample Code (to reproduce the issue)
```ts
// In any controller
ctx.response.header('Content-Type', 'application/pdf');
ctx.response.flushHeaders(200);
// If I don't execute this line, the headers are not sent over the network
ctx.response.response.flushHeaders();

// ... do something async
ctx.response.response.end(data);
```

In adonis response, calling `flushHeaders` calls `writeHead` on the response stream
https://github.com/adonisjs/http-server/blob/6cc8708efcd4b53b0cbc0a965660f9d2f4d16f98/src/Response/index.ts#L507

But when calling `writeHead`, the headers actually get flushed only given this "except" condition:
https://github.com/nodejs/node/blob/ccf46ba0f5ce02ae85b8bdb5e29acfc376caf9fc/lib/_http_outgoing.js#L547

You are supposed to call `flushHeaders` on the response stream to start sending data over the network

Some context about why I'm using adonisjs in this weird way:
- The controller is called when a user wants to download a file which is generated on the fly (doesn't exist on disk yet). The generation takes some time but I want the browser's file download UI to appear right away. Otherwise it might seem like the action is doing nothing.
- The file does not exist yet, so I cannot use a stream to do that.

Disclaimer: I'm not familiar with how the node http library works so this is just my take and I might be wrong. However in a real adonis application I observed that `flushHeaders` did not actually send the headers which seems like a bug to me. Calling `ctx.response.response.flushHeaders()` fixed the issue.

**Comment by RomainLanz** [comment]
Hey @stropitek! 👋🏻 

Yes, it seems that we are not following what `Node.js` [is doing](https://nodejs.org/dist/latest-v18.x/docs/api/http.html#requestflushheaders).

I am not sure how much this change would be a breaking change.
We must also change the behavior in V6 (`next` branch).

What is your opinion @thetutlage?

**Comment by thetutlage** [comment]
This is intentional, AdonisJS `response.header` does not follow the semantics of `response.setHeader`. We write headers in one go using `res.write`.

I am not sure why this creates any problem. Maybe @stropitek can share a code example of what exactly they are doing and then I can share the right way to do it.

**Comment by stropitek** [comment]
The use case is: I am downloading a resource, but it's generated on request and thus can't be streamed. But I want the download interface to appear immediately when the link is clicked. Sending the headers right away is a very convenient way to give immediate feedback to the user that the download has started, without custom logic.

Here is how I implemented it:

```ts
response.header('Content-Type', 'application/pdf');
response.header(
  'Content-Disposition',
  `attachment; filename="${filename}"`,
);

response.flushHeaders(200);
// If this is not called, the headers are not sent over the network.
response.response.flushHeaders();

try {
  // This takes a few seconds
  const buffer = await writePdf();
  response.response.end(buffer);
} catch (error) {
  // It's too late to send a failure status code
  // The headers have already been sent
  logger.error(`Failed to generate pdf from ${frontUrl.href} `, error);
  response.response.destroy();
}
```

A side note: originally I want to call `response.abort()` in the catch block but that did not have any effect. The request would just hang. I also found that behaviour surprising and wanted to file another issue.


Since then, I've realised that the overall strategy is incompatible with having nginx in between the client and the adonis server (due to how nginx buffers data). The headers cannot be sent immediately by nginx without completely deactivating buffering. So I've given up on the overall strategy.

**Comment by targos** [comment]
I think the main point is that the `flushHeaders` API of AdonisJS is very confusing because it doesn't do what the name implies (and what Node.js does)

**Comment by thetutlage** [comment]
I am still confused with what exactly the issue is.

- Is it the method name is confusing? 
- Is it the method is buggy?
- Or something else?

@stropitek You are having issues, because you are using a mix of APIs from the AdonisJS response object and then also directly reaching for the Node.js `res` object. You can re-rewrite your code as follows.

```ts
response.header('content-Type', 'application/pdf')
response.header(
  'content-disposition',
  `attachment; filename="${filename}"`,
)

try {
  const buffer = await writePdf();
  response.send(buffer);
} catch (error) {
  response.removeHeader('content-type')
  response.removeHeader('content-disposition')
  response.send(error.message)
}
```

**Comment by RomainLanz** [comment]
> I am still confused with what exactly the issue is.

Adonis's `flushHeaders` method does not follow what Node's `flushHeaders` is doing.

**Comment by thetutlage** [comment]
> Adonis's flushHeaders method does not follow what Node's flushHeaders is doing.

It's not written anywhere in the docs that it is supposed to that what Node.js does. 

What that said, I wasn't even aware that Node.js had this method too. Yes, it can be confusing, but, the intent of AdonisJS `response.flushHeaders` is not same as Node.js `response.flushHeaders`. Maybe, we can rename it.

But this method is meant to be used internally within the package, that is the reason it was never documented publicly.

**Comment by stropitek** [comment]
> @stropitek You are having issues, because you are using a mix of APIs from the AdonisJS response object and then also directly reaching for the Node.js `res` object. You can re-rewrite your code as follows.

I know this is not recommended, but what I tried to achieve what not possible using only adonisjs api. The code you gave would wait until the PDF is generated to send the first bytes. Therefore when clicking a download link, there is a lag between the click and the download UI appearing, which I wanted to prevent.

Anyway as said, the main reason for this issue was not about my use case (which I gave because you asked for it), but because it's confusing to have a method `flushHeaders` which does not actually do what it says. I expect headers to be sent over the network when `flushHeaders` is called. I also think it helps to mimic when possible the semantics of Node.js.

**Comment by stropitek** [comment]
PS: when I am talking about the download UI, I'm talking about the browser UI, not my app's UI

**Comment by thetutlage** [comment]
@stropitek I agree about the confusion and it is basically because of my ignorance around knowing that Node.js has a similar function. 

We will rename it in v6 (since it is going to be a breaking change).

**Comment by thetutlage** [comment]
Renamed the method to `relayHeaders`. Basically, it relays the headers set with AdonisJS `response` object to Node.js `res` object. I hope that will remove the confusion :)

https://github.com/adonisjs/http-server/releases/tag/v7.0.0-0
