### ISSUE TITLE
The class method `onFinish` for the response class not exists

### ISSUE THREAD

**Issue by ad-momo** [adonisjs/http-server#82]
Hello,

In the part [Running actions after response finishes](https://docs.adonisjs.com/guides/response#running-actions-after-response-finishes) the class method `onFinish` for the [response class](https://github.com/adonisjs/http-server/blob/main/src/response.ts) not exists.

Please update the documentation to achieve this.

Maybe like this ? :
```ts
onFinished(response.response, (err, res) => {})
```

Thanks 😃

**Comment by thetutlage** [comment]
Thanks for reporting. I have added the method to the response class. https://github.com/adonisjs/http-server/releases/tag/v7.2.0
