### ISSUE TITLE
Adonis does not respond JSON:API errors

### ISSUE THREAD

**Issue by AlexandreGerault** [adonisjs/http-server#86]
### Package version

7.2.3

### Describe the bug

I'm doing a JSON:API with adonis.js 6. I'm testing validation errors, and as I read in the documentation,  I'm expecting JSON:API errors as I am sending the `Accept: application/vnd.api+json` header.

However, I got the "normal" json response. I made this little repository to reproduce the error: https://github.com/AlexandreGerault/adonis-jsonapi-error

There is a test that reproduces my issue:
```ts
test('returns json api error when email invalid', async ({ assert, client }) => {
  const response = await client
    .post('/login')
    .json({
      email: 'corentin@thomas',
      password: 'P@ssw0rd!?',
    })
    .header('Accept', 'application/vnd.api+json')
    .send()

  response.assertBodyContains({
    errors: [
      {
        title: 'The email field must be a valid email address',
        code: 'email',
        source: { pointer: 'email' },
      },
    ],
  })
})
```

Reading the source code of the package I played with the `renderValidationError` function, and I tried to bypass the switch condition, returning directly with `renderValidationErrorAsJSONAPI`. Doing this make the test pass green.

I guess there is something I might be doing wrong that is related to `ctx.request.accepts(["html", "application/vnd.api+json", "json"])` piece of code. Indeed, with my test, if I log the result of this accepts function, it returns only "json" 🤔 

Any idea where it could comes from? Also I'm open to try fixing it if that is not intended 

### Reproduction repo

[adonis-jsonapi-error](https://github.com/AlexandreGerault/adonis-jsonapi-error)

**Comment by RomainLanz** [comment]
Hey @AlexandreGerault! 👋🏻 

It seems that you have a middleware in the server stack that forces the `Accept` header to `application/json`.

```ts
export default class ForceJsonResponseMiddleware {
  async handle({ request }: HttpContext, next: NextFn) {
    const headers = request.headers()
    headers.accept = 'application/json'

    return next()
  }
}
```

📁  https://github.com/AlexandreGerault/adonis-jsonapi-error/blob/main/app/middleware/force_json_response_middleware.ts#L10

**Comment by AlexandreGerault** [comment]
Indeed you're right, I didn't notice that middleware. Must be set when starting a project as API 👍 

I don't remember this to be documented (I mean it is somehow here https://docs.adonisjs.com/guides/getting-started/installation#api-starter-kit) to explicitly enforce the `application/json` accept header.

I was thinking about documenting this a bit more explicitly but after thoughts, it seems only validation error (or some errors) is ready for JSON:API specs. Nothing in the entity serialization seems to be JSON:API compatible (yet?), thus I guess I might better work with the `application/json` only 🤔 

I close this issue but might start a discussion then about this 😄
